language: node_js
node_js:
  - "node"
install:
  - npm ci
script:
  - npm run lint
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script:
    - npm run build && rm ./build/static/js/*.js.map && now build --public --name stylelint-config-generator --token $NOW_TOKEN && now alias --token $NOW_TOKEN
