language: node_js
node_js:
  - "node"
install:
  - yarn
script:
  - yarn lint
  - yarn lint:css
  - yarn lint:sc
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script:
    - yarn build && now build --public --name stylelint-config-generator --token $NOW_TOKEN && now alias --token $NOW_TOKEN --force
